# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('sun-harvester-example', ['sun-harvester'])
    obj.source = 'sun-harvester-example.cc'

